############## Removeremos estas duas rotas tbm
#model_author:
#    resource: "@ModelBundle/Controller/AuthorController.php"
#    type:     annotation
#
#model_post:
#    resource: "@ModelBundle/Controller/PostController.php"
#    type:     annotation


################ Removemos pois não iremos mais precisar
#model_bundle: # adicionamos esta rota somente para vermos a aplicação rodando
#    resource: "@ModelBundle/Controller/"
#    type:     annotation
#    prefix:   /

######## Não queremos que o symfony crie a rota para este Bundle, por isso a removeremos......
# model:
#     resource: "@ModelBundle/Controller/"
#     type:     annotation
#     prefix:   /

core:
    resource: "@CoreBundle/Controller/"
    type:     annotation
    prefix:   /

# model:
#     resource: "@ModelBundle/Controller/"
#     type:     annotation
#     prefix:   /model

### Devemos excluir a rota do bundle que apagamos:

# app:
#     resource: '@AppBundle/Controller/'
#     type: annotation

### Import FOSUserBundle routing files
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
#############################
# FOSUser
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile