<?php

namespace ModelBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{

    private function getQueryBuilder()
    {
        $em = $this->getEntityManager();

        $queryBuilder = $em->getRepository('ModelBundle:Post')->createQueryBuilder('posts');

        return $queryBuilder;
    }

    public function findAllInOrder()
    {
        $qb = $this->getQueryBuilder()->orderBy('posts.createdAt', 'desc');

        return $qb->getQuery()->getResult();
    }
}
